apiVersion: v1
kind: ServiceAccount
metadata:
  name: operatortest
  namespace: gpu
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operatortest
  namespace: gpu
subjects:
- kind: ServiceAccount
  name: operatortest
  namespace: gpu
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: operatortest
  namespace: gpu
  labels:
    app: operatortest
spec:
  type: NodePort
  ports:
  - port: 10100
    targetPort: 10100
    protocol: TCP
    nodePort: 30036
  selector:
    app: operatortest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operatortest
  namespace: gpu
  labels:
    app: operatortest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operatortest
  template:
    metadata:
      labels:
        app: operatortest
    spec:
      serviceAccountName: operatortest
      nodeName: nongpuserver
      containers:
      - name: operatortest
        image: ketidevit2/kmc-operator-test:v26
        ports:
        - containerPort: 10100
        # args:
        # - operator
        # - --loginip=10.0.5.24
        # - --port=6820
        # - --operatorport=10100
        volumeMounts:
        - name: jwtkey
          mountPath: /etc/slurm
      volumes:
      - name: jwtkey
        hostPath: 
          path: /etc/slurm