# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import data_pb2 as protos_dot_data__pb2


class UserStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPod = channel.unary_unary(
                '/v1.user.User/GetPod',
                request_serializer=protos_dot_data__pb2.GetPodRequest.SerializeToString,
                response_deserializer=protos_dot_data__pb2.GetPodResponse.FromString,
                )
        self.PostPod = channel.unary_unary(
                '/v1.user.User/PostPod',
                request_serializer=protos_dot_data__pb2.PostPodRequest.SerializeToString,
                response_deserializer=protos_dot_data__pb2.PostPodResponse.FromString,
                )
        self.GetJob = channel.unary_unary(
                '/v1.user.User/GetJob',
                request_serializer=protos_dot_data__pb2.GetJobRequest.SerializeToString,
                response_deserializer=protos_dot_data__pb2.GetJobResponse.FromString,
                )


class UserServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PostPod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPod': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPod,
                    request_deserializer=protos_dot_data__pb2.GetPodRequest.FromString,
                    response_serializer=protos_dot_data__pb2.GetPodResponse.SerializeToString,
            ),
            'PostPod': grpc.unary_unary_rpc_method_handler(
                    servicer.PostPod,
                    request_deserializer=protos_dot_data__pb2.PostPodRequest.FromString,
                    response_serializer=protos_dot_data__pb2.PostPodResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=protos_dot_data__pb2.GetJobRequest.FromString,
                    response_serializer=protos_dot_data__pb2.GetJobResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'v1.user.User', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class User(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.user.User/GetPod',
            protos_dot_data__pb2.GetPodRequest.SerializeToString,
            protos_dot_data__pb2.GetPodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PostPod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.user.User/PostPod',
            protos_dot_data__pb2.PostPodRequest.SerializeToString,
            protos_dot_data__pb2.PostPodResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/v1.user.User/GetJob',
            protos_dot_data__pb2.GetJobRequest.SerializeToString,
            protos_dot_data__pb2.GetJobResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
