# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/data.proto',
  package='v1.user',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11protos/data.proto\x12\x07v1.user\"\x8d\x01\n\nPodMessage\x12\x11\n\tnamespace\x18\x01 \x01(\t\x12\x10\n\x08pod_name\x18\x02 \x01(\t\x12\r\n\x05ready\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0f\n\x07restart\x18\x05 \x01(\t\x12\x0b\n\x03\x61ge\x18\x06 \x01(\t\x12\n\n\x02ip\x18\x07 \x01(\t\x12\x11\n\tnode_name\x18\x08 \x01(\t\"#\n\rGetPodRequest\x12\x12\n\nname_space\x18\x01 \x01(\t\":\n\x0eGetPodResponse\x12(\n\x0bpod_message\x18\x01 \x01(\x0b\x32\x13.v1.user.PodMessage\"\"\n\x0ePostPodMessage\x12\x10\n\x08yamldata\x18\x01 \x01(\t\"#\n\x0ePostPodRequest\x12\x11\n\tyaml_data\x18\x01 \x01(\t\"D\n\x0fPostPodResponse\x12\x31\n\x10post_pod_message\x18\x01 \x01(\x0b\x32\x17.v1.user.PostPodMessage\"\x82\x01\n\nJobMessage\x12\x0f\n\x07\x61\x63\x63ount\x18\x01 \x01(\t\x12\x11\n\tnode_name\x18\x02 \x01(\t\x12\x11\n\tjob_state\x18\x03 \x01(\t\x12\x10\n\x08job_name\x18\x04 \x01(\t\x12\x12\n\nstart_time\x18\x05 \x01(\t\x12\x17\n\x0fstandard_output\x18\x06 \x01(\t\"\"\n\rGetJobRequest\x12\x11\n\tnode_name\x18\x01 \x01(\t\">\n\x0eGetJobResponse\x12,\n\x0fget_job_message\x18\x01 \x01(\x0b\x32\x13.v1.user.JobMessage2\xba\x01\n\x04User\x12\x39\n\x06GetPod\x12\x16.v1.user.GetPodRequest\x1a\x17.v1.user.GetPodResponse\x12<\n\x07PostPod\x12\x17.v1.user.PostPodRequest\x1a\x18.v1.user.PostPodResponse\x12\x39\n\x06GetJob\x12\x16.v1.user.GetJobRequest\x1a\x17.v1.user.GetJobResponseb\x06proto3'
)




_PODMESSAGE = _descriptor.Descriptor(
  name='PodMessage',
  full_name='v1.user.PodMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='namespace', full_name='v1.user.PodMessage.namespace', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pod_name', full_name='v1.user.PodMessage.pod_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ready', full_name='v1.user.PodMessage.ready', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='v1.user.PodMessage.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='restart', full_name='v1.user.PodMessage.restart', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='age', full_name='v1.user.PodMessage.age', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ip', full_name='v1.user.PodMessage.ip', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='v1.user.PodMessage.node_name', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=172,
)


_GETPODREQUEST = _descriptor.Descriptor(
  name='GetPodRequest',
  full_name='v1.user.GetPodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name_space', full_name='v1.user.GetPodRequest.name_space', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=174,
  serialized_end=209,
)


_GETPODRESPONSE = _descriptor.Descriptor(
  name='GetPodResponse',
  full_name='v1.user.GetPodResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pod_message', full_name='v1.user.GetPodResponse.pod_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=211,
  serialized_end=269,
)


_POSTPODMESSAGE = _descriptor.Descriptor(
  name='PostPodMessage',
  full_name='v1.user.PostPodMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='yamldata', full_name='v1.user.PostPodMessage.yamldata', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=271,
  serialized_end=305,
)


_POSTPODREQUEST = _descriptor.Descriptor(
  name='PostPodRequest',
  full_name='v1.user.PostPodRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='yaml_data', full_name='v1.user.PostPodRequest.yaml_data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=342,
)


_POSTPODRESPONSE = _descriptor.Descriptor(
  name='PostPodResponse',
  full_name='v1.user.PostPodResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='post_pod_message', full_name='v1.user.PostPodResponse.post_pod_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=344,
  serialized_end=412,
)


_JOBMESSAGE = _descriptor.Descriptor(
  name='JobMessage',
  full_name='v1.user.JobMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='v1.user.JobMessage.account', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='node_name', full_name='v1.user.JobMessage.node_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_state', full_name='v1.user.JobMessage.job_state', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='job_name', full_name='v1.user.JobMessage.job_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_time', full_name='v1.user.JobMessage.start_time', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='standard_output', full_name='v1.user.JobMessage.standard_output', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=545,
)


_GETJOBREQUEST = _descriptor.Descriptor(
  name='GetJobRequest',
  full_name='v1.user.GetJobRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node_name', full_name='v1.user.GetJobRequest.node_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=547,
  serialized_end=581,
)


_GETJOBRESPONSE = _descriptor.Descriptor(
  name='GetJobResponse',
  full_name='v1.user.GetJobResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='get_job_message', full_name='v1.user.GetJobResponse.get_job_message', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=583,
  serialized_end=645,
)

_GETPODRESPONSE.fields_by_name['pod_message'].message_type = _PODMESSAGE
_POSTPODRESPONSE.fields_by_name['post_pod_message'].message_type = _POSTPODMESSAGE
_GETJOBRESPONSE.fields_by_name['get_job_message'].message_type = _JOBMESSAGE
DESCRIPTOR.message_types_by_name['PodMessage'] = _PODMESSAGE
DESCRIPTOR.message_types_by_name['GetPodRequest'] = _GETPODREQUEST
DESCRIPTOR.message_types_by_name['GetPodResponse'] = _GETPODRESPONSE
DESCRIPTOR.message_types_by_name['PostPodMessage'] = _POSTPODMESSAGE
DESCRIPTOR.message_types_by_name['PostPodRequest'] = _POSTPODREQUEST
DESCRIPTOR.message_types_by_name['PostPodResponse'] = _POSTPODRESPONSE
DESCRIPTOR.message_types_by_name['JobMessage'] = _JOBMESSAGE
DESCRIPTOR.message_types_by_name['GetJobRequest'] = _GETJOBREQUEST
DESCRIPTOR.message_types_by_name['GetJobResponse'] = _GETJOBRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PodMessage = _reflection.GeneratedProtocolMessageType('PodMessage', (_message.Message,), {
  'DESCRIPTOR' : _PODMESSAGE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.PodMessage)
  })
_sym_db.RegisterMessage(PodMessage)

GetPodRequest = _reflection.GeneratedProtocolMessageType('GetPodRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETPODREQUEST,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.GetPodRequest)
  })
_sym_db.RegisterMessage(GetPodRequest)

GetPodResponse = _reflection.GeneratedProtocolMessageType('GetPodResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETPODRESPONSE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.GetPodResponse)
  })
_sym_db.RegisterMessage(GetPodResponse)

PostPodMessage = _reflection.GeneratedProtocolMessageType('PostPodMessage', (_message.Message,), {
  'DESCRIPTOR' : _POSTPODMESSAGE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.PostPodMessage)
  })
_sym_db.RegisterMessage(PostPodMessage)

PostPodRequest = _reflection.GeneratedProtocolMessageType('PostPodRequest', (_message.Message,), {
  'DESCRIPTOR' : _POSTPODREQUEST,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.PostPodRequest)
  })
_sym_db.RegisterMessage(PostPodRequest)

PostPodResponse = _reflection.GeneratedProtocolMessageType('PostPodResponse', (_message.Message,), {
  'DESCRIPTOR' : _POSTPODRESPONSE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.PostPodResponse)
  })
_sym_db.RegisterMessage(PostPodResponse)

JobMessage = _reflection.GeneratedProtocolMessageType('JobMessage', (_message.Message,), {
  'DESCRIPTOR' : _JOBMESSAGE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.JobMessage)
  })
_sym_db.RegisterMessage(JobMessage)

GetJobRequest = _reflection.GeneratedProtocolMessageType('GetJobRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBREQUEST,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.GetJobRequest)
  })
_sym_db.RegisterMessage(GetJobRequest)

GetJobResponse = _reflection.GeneratedProtocolMessageType('GetJobResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETJOBRESPONSE,
  '__module__' : 'protos.data_pb2'
  # @@protoc_insertion_point(class_scope:v1.user.GetJobResponse)
  })
_sym_db.RegisterMessage(GetJobResponse)



_USER = _descriptor.ServiceDescriptor(
  name='User',
  full_name='v1.user.User',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=648,
  serialized_end=834,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPod',
    full_name='v1.user.User.GetPod',
    index=0,
    containing_service=None,
    input_type=_GETPODREQUEST,
    output_type=_GETPODRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PostPod',
    full_name='v1.user.User.PostPod',
    index=1,
    containing_service=None,
    input_type=_POSTPODREQUEST,
    output_type=_POSTPODRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetJob',
    full_name='v1.user.User.GetJob',
    index=2,
    containing_service=None,
    input_type=_GETJOBREQUEST,
    output_type=_GETJOBRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_USER)

DESCRIPTOR.services_by_name['User'] = _USER

# @@protoc_insertion_point(module_scope)
